export interface MasterIngredient {
  id?: string;
  itemCode: string;
  majorGroup: string | null;
  category: string | null;
  subCategory: string | null;
  product: string;
  vendor: string;
  caseSize: string;
  unitsPerCase: string;
  currentPrice: number;
  unitOfMeasure: string;
  recipeUnitPerPurchaseUnit: number;
  recipeUnitType: string;
  yieldPercent: number;
  costPerRecipeUnit: number;
  imageUrl?: string;
  storageArea?: string;
  allergenPeanut: boolean;
  allergenCrustacean: boolean;
  allergenTreenut: boolean;
  allergenShellfish: boolean;
  allergenSesame: boolean;
  allergenSoy: boolean;
  allergenFish: boolean;
  allergenWheat: boolean;
  allergenMilk: boolean;
  allergenSulphite: boolean;
  allergenEgg: boolean;
  allergenGluten: boolean;
  allergenMustard: boolean;
  allergenCelery: boolean;
  allergenGarlic: boolean;
  allergenOnion: boolean;
  allergenNitrite: boolean;
  allergenMushroom: boolean;
  allergenHotPepper: boolean;
  allergenCitrus: boolean;
  allergenPork: boolean;
  allergenCustom1Name: string;
  allergenCustom1Active: boolean;
  allergenCustom2Name: string;
  allergenCustom2Active: boolean;
  allergenCustom3Name: string;
  allergenCustom3Active: boolean;
  allergenNotes: string;
  lastUpdated?: string;
  // Display names from relationships
  majorGroupName?: string;
  categoryName?: string;
  subCategoryName?: string;
}