-- Create tables for 7shifts mappings
CREATE TABLE location_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sevenshift_id VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  external_id VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE department_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sevenshift_id VARCHAR NOT NULL,
  location_id VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  external_id VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE role_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sevenshift_id VARCHAR NOT NULL,
  department_id VARCHAR NOT NULL,
  location_id VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  external_id VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE user_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sevenshift_id VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  role_ids VARCHAR[] NOT NULL,
  external_id VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add RLS policies
ALTER TABLE location_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE department_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_mappings ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow authenticated access to location_mappings"
  ON location_mappings FOR ALL
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated access to department_mappings"
  ON department_mappings FOR ALL
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated access to role_mappings"
  ON role_mappings FOR ALL
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated access to user_mappings"
  ON user_mappings FOR ALL
  TO authenticated
  USING (true);